/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WallOfShameRouteImport } from './routes/wall-of-shame'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as NavigateRouteImport } from './routes/navigate'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContractorRouteImport } from './routes/contractor'
import { Route as CitizenRouteImport } from './routes/citizen'
import { Route as MunicipalRouteImport } from './routes/_municipal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login.index'
import { Route as SignupContractorRouteImport } from './routes/signup.contractor'
import { Route as SignupCitizenRouteImport } from './routes/signup.citizen'
import { Route as LoginMunicipalRouteImport } from './routes/login.municipal'
import { Route as ContractorRejectedRouteImport } from './routes/contractor_.rejected'
import { Route as ContractorPendingRouteImport } from './routes/contractor_.pending'
import { Route as ContractorBlacklistedRouteImport } from './routes/contractor_.blacklisted'
import { Route as MunicipalReportsRouteImport } from './routes/_municipal.reports'
import { Route as MunicipalDetectionRouteImport } from './routes/_municipal.detection'
import { Route as MunicipalDashboardRouteImport } from './routes/_municipal.dashboard'
import { Route as MunicipalContractorsRouteImport } from './routes/_municipal.contractors'
import { Route as MunicipalBudgetRouteImport } from './routes/_municipal.budget'
import { Route as MunicipalAlertsRouteImport } from './routes/_municipal.alerts'

const WallOfShameRoute = WallOfShameRouteImport.update({
  id: '/wall-of-shame',
  path: '/wall-of-shame',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigateRoute = NavigateRouteImport.update({
  id: '/navigate',
  path: '/navigate',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorRoute = ContractorRouteImport.update({
  id: '/contractor',
  path: '/contractor',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRoute = CitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const MunicipalRoute = MunicipalRouteImport.update({
  id: '/_municipal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRoute,
} as any)
const SignupContractorRoute = SignupContractorRouteImport.update({
  id: '/contractor',
  path: '/contractor',
  getParentRoute: () => SignupRoute,
} as any)
const SignupCitizenRoute = SignupCitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => SignupRoute,
} as any)
const LoginMunicipalRoute = LoginMunicipalRouteImport.update({
  id: '/municipal',
  path: '/municipal',
  getParentRoute: () => LoginRoute,
} as any)
const ContractorRejectedRoute = ContractorRejectedRouteImport.update({
  id: '/contractor_/rejected',
  path: '/contractor/rejected',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorPendingRoute = ContractorPendingRouteImport.update({
  id: '/contractor_/pending',
  path: '/contractor/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorBlacklistedRoute = ContractorBlacklistedRouteImport.update({
  id: '/contractor_/blacklisted',
  path: '/contractor/blacklisted',
  getParentRoute: () => rootRouteImport,
} as any)
const MunicipalReportsRoute = MunicipalReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => MunicipalRoute,
} as any)
const MunicipalDetectionRoute = MunicipalDetectionRouteImport.update({
  id: '/detection',
  path: '/detection',
  getParentRoute: () => MunicipalRoute,
} as any)
const MunicipalDashboardRoute = MunicipalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => MunicipalRoute,
} as any)
const MunicipalContractorsRoute = MunicipalContractorsRouteImport.update({
  id: '/contractors',
  path: '/contractors',
  getParentRoute: () => MunicipalRoute,
} as any)
const MunicipalBudgetRoute = MunicipalBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => MunicipalRoute,
} as any)
const MunicipalAlertsRoute = MunicipalAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => MunicipalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/citizen': typeof CitizenRoute
  '/contractor': typeof ContractorRoute
  '/login': typeof LoginRouteWithChildren
  '/navigate': typeof NavigateRoute
  '/signup': typeof SignupRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/verify': typeof VerifyRoute
  '/wall-of-shame': typeof WallOfShameRoute
  '/alerts': typeof MunicipalAlertsRoute
  '/budget': typeof MunicipalBudgetRoute
  '/contractors': typeof MunicipalContractorsRoute
  '/dashboard': typeof MunicipalDashboardRoute
  '/detection': typeof MunicipalDetectionRoute
  '/reports': typeof MunicipalReportsRoute
  '/contractor/blacklisted': typeof ContractorBlacklistedRoute
  '/contractor/pending': typeof ContractorPendingRoute
  '/contractor/rejected': typeof ContractorRejectedRoute
  '/login/municipal': typeof LoginMunicipalRoute
  '/signup/citizen': typeof SignupCitizenRoute
  '/signup/contractor': typeof SignupContractorRoute
  '/login/': typeof LoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/citizen': typeof CitizenRoute
  '/contractor': typeof ContractorRoute
  '/navigate': typeof NavigateRoute
  '/signup': typeof SignupRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/verify': typeof VerifyRoute
  '/wall-of-shame': typeof WallOfShameRoute
  '/alerts': typeof MunicipalAlertsRoute
  '/budget': typeof MunicipalBudgetRoute
  '/contractors': typeof MunicipalContractorsRoute
  '/dashboard': typeof MunicipalDashboardRoute
  '/detection': typeof MunicipalDetectionRoute
  '/reports': typeof MunicipalReportsRoute
  '/contractor/blacklisted': typeof ContractorBlacklistedRoute
  '/contractor/pending': typeof ContractorPendingRoute
  '/contractor/rejected': typeof ContractorRejectedRoute
  '/login/municipal': typeof LoginMunicipalRoute
  '/signup/citizen': typeof SignupCitizenRoute
  '/signup/contractor': typeof SignupContractorRoute
  '/login': typeof LoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_municipal': typeof MunicipalRouteWithChildren
  '/citizen': typeof CitizenRoute
  '/contractor': typeof ContractorRoute
  '/login': typeof LoginRouteWithChildren
  '/navigate': typeof NavigateRoute
  '/signup': typeof SignupRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/verify': typeof VerifyRoute
  '/wall-of-shame': typeof WallOfShameRoute
  '/_municipal/alerts': typeof MunicipalAlertsRoute
  '/_municipal/budget': typeof MunicipalBudgetRoute
  '/_municipal/contractors': typeof MunicipalContractorsRoute
  '/_municipal/dashboard': typeof MunicipalDashboardRoute
  '/_municipal/detection': typeof MunicipalDetectionRoute
  '/_municipal/reports': typeof MunicipalReportsRoute
  '/contractor_/blacklisted': typeof ContractorBlacklistedRoute
  '/contractor_/pending': typeof ContractorPendingRoute
  '/contractor_/rejected': typeof ContractorRejectedRoute
  '/login/municipal': typeof LoginMunicipalRoute
  '/signup/citizen': typeof SignupCitizenRoute
  '/signup/contractor': typeof SignupContractorRoute
  '/login/': typeof LoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/citizen'
    | '/contractor'
    | '/login'
    | '/navigate'
    | '/signup'
    | '/unauthorized'
    | '/verify'
    | '/wall-of-shame'
    | '/alerts'
    | '/budget'
    | '/contractors'
    | '/dashboard'
    | '/detection'
    | '/reports'
    | '/contractor/blacklisted'
    | '/contractor/pending'
    | '/contractor/rejected'
    | '/login/municipal'
    | '/signup/citizen'
    | '/signup/contractor'
    | '/login/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/citizen'
    | '/contractor'
    | '/navigate'
    | '/signup'
    | '/unauthorized'
    | '/verify'
    | '/wall-of-shame'
    | '/alerts'
    | '/budget'
    | '/contractors'
    | '/dashboard'
    | '/detection'
    | '/reports'
    | '/contractor/blacklisted'
    | '/contractor/pending'
    | '/contractor/rejected'
    | '/login/municipal'
    | '/signup/citizen'
    | '/signup/contractor'
    | '/login'
  id:
    | '__root__'
    | '/'
    | '/_municipal'
    | '/citizen'
    | '/contractor'
    | '/login'
    | '/navigate'
    | '/signup'
    | '/unauthorized'
    | '/verify'
    | '/wall-of-shame'
    | '/_municipal/alerts'
    | '/_municipal/budget'
    | '/_municipal/contractors'
    | '/_municipal/dashboard'
    | '/_municipal/detection'
    | '/_municipal/reports'
    | '/contractor_/blacklisted'
    | '/contractor_/pending'
    | '/contractor_/rejected'
    | '/login/municipal'
    | '/signup/citizen'
    | '/signup/contractor'
    | '/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MunicipalRoute: typeof MunicipalRouteWithChildren
  CitizenRoute: typeof CitizenRoute
  ContractorRoute: typeof ContractorRoute
  LoginRoute: typeof LoginRouteWithChildren
  NavigateRoute: typeof NavigateRoute
  SignupRoute: typeof SignupRouteWithChildren
  UnauthorizedRoute: typeof UnauthorizedRoute
  VerifyRoute: typeof VerifyRoute
  WallOfShameRoute: typeof WallOfShameRoute
  ContractorBlacklistedRoute: typeof ContractorBlacklistedRoute
  ContractorPendingRoute: typeof ContractorPendingRoute
  ContractorRejectedRoute: typeof ContractorRejectedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wall-of-shame': {
      id: '/wall-of-shame'
      path: '/wall-of-shame'
      fullPath: '/wall-of-shame'
      preLoaderRoute: typeof WallOfShameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigate': {
      id: '/navigate'
      path: '/navigate'
      fullPath: '/navigate'
      preLoaderRoute: typeof NavigateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractor': {
      id: '/contractor'
      path: '/contractor'
      fullPath: '/contractor'
      preLoaderRoute: typeof ContractorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen': {
      id: '/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof CitizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_municipal': {
      id: '/_municipal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MunicipalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRoute
    }
    '/signup/contractor': {
      id: '/signup/contractor'
      path: '/contractor'
      fullPath: '/signup/contractor'
      preLoaderRoute: typeof SignupContractorRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signup/citizen': {
      id: '/signup/citizen'
      path: '/citizen'
      fullPath: '/signup/citizen'
      preLoaderRoute: typeof SignupCitizenRouteImport
      parentRoute: typeof SignupRoute
    }
    '/login/municipal': {
      id: '/login/municipal'
      path: '/municipal'
      fullPath: '/login/municipal'
      preLoaderRoute: typeof LoginMunicipalRouteImport
      parentRoute: typeof LoginRoute
    }
    '/contractor_/rejected': {
      id: '/contractor_/rejected'
      path: '/contractor/rejected'
      fullPath: '/contractor/rejected'
      preLoaderRoute: typeof ContractorRejectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractor_/pending': {
      id: '/contractor_/pending'
      path: '/contractor/pending'
      fullPath: '/contractor/pending'
      preLoaderRoute: typeof ContractorPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractor_/blacklisted': {
      id: '/contractor_/blacklisted'
      path: '/contractor/blacklisted'
      fullPath: '/contractor/blacklisted'
      preLoaderRoute: typeof ContractorBlacklistedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_municipal/reports': {
      id: '/_municipal/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof MunicipalReportsRouteImport
      parentRoute: typeof MunicipalRoute
    }
    '/_municipal/detection': {
      id: '/_municipal/detection'
      path: '/detection'
      fullPath: '/detection'
      preLoaderRoute: typeof MunicipalDetectionRouteImport
      parentRoute: typeof MunicipalRoute
    }
    '/_municipal/dashboard': {
      id: '/_municipal/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof MunicipalDashboardRouteImport
      parentRoute: typeof MunicipalRoute
    }
    '/_municipal/contractors': {
      id: '/_municipal/contractors'
      path: '/contractors'
      fullPath: '/contractors'
      preLoaderRoute: typeof MunicipalContractorsRouteImport
      parentRoute: typeof MunicipalRoute
    }
    '/_municipal/budget': {
      id: '/_municipal/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof MunicipalBudgetRouteImport
      parentRoute: typeof MunicipalRoute
    }
    '/_municipal/alerts': {
      id: '/_municipal/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof MunicipalAlertsRouteImport
      parentRoute: typeof MunicipalRoute
    }
  }
}

interface MunicipalRouteChildren {
  MunicipalAlertsRoute: typeof MunicipalAlertsRoute
  MunicipalBudgetRoute: typeof MunicipalBudgetRoute
  MunicipalContractorsRoute: typeof MunicipalContractorsRoute
  MunicipalDashboardRoute: typeof MunicipalDashboardRoute
  MunicipalDetectionRoute: typeof MunicipalDetectionRoute
  MunicipalReportsRoute: typeof MunicipalReportsRoute
}

const MunicipalRouteChildren: MunicipalRouteChildren = {
  MunicipalAlertsRoute: MunicipalAlertsRoute,
  MunicipalBudgetRoute: MunicipalBudgetRoute,
  MunicipalContractorsRoute: MunicipalContractorsRoute,
  MunicipalDashboardRoute: MunicipalDashboardRoute,
  MunicipalDetectionRoute: MunicipalDetectionRoute,
  MunicipalReportsRoute: MunicipalReportsRoute,
}

const MunicipalRouteWithChildren = MunicipalRoute._addFileChildren(
  MunicipalRouteChildren,
)

interface LoginRouteChildren {
  LoginMunicipalRoute: typeof LoginMunicipalRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginMunicipalRoute: LoginMunicipalRoute,
  LoginIndexRoute: LoginIndexRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

interface SignupRouteChildren {
  SignupCitizenRoute: typeof SignupCitizenRoute
  SignupContractorRoute: typeof SignupContractorRoute
}

const SignupRouteChildren: SignupRouteChildren = {
  SignupCitizenRoute: SignupCitizenRoute,
  SignupContractorRoute: SignupContractorRoute,
}

const SignupRouteWithChildren =
  SignupRoute._addFileChildren(SignupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MunicipalRoute: MunicipalRouteWithChildren,
  CitizenRoute: CitizenRoute,
  ContractorRoute: ContractorRoute,
  LoginRoute: LoginRouteWithChildren,
  NavigateRoute: NavigateRoute,
  SignupRoute: SignupRouteWithChildren,
  UnauthorizedRoute: UnauthorizedRoute,
  VerifyRoute: VerifyRoute,
  WallOfShameRoute: WallOfShameRoute,
  ContractorBlacklistedRoute: ContractorBlacklistedRoute,
  ContractorPendingRoute: ContractorPendingRoute,
  ContractorRejectedRoute: ContractorRejectedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
