/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NavigateRouteImport } from './routes/navigate'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContractorRouteImport } from './routes/contractor'
import { Route as CitizenRouteImport } from './routes/citizen'
import { Route as MunicipalRouteImport } from './routes/_municipal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MunicipalReportsRouteImport } from './routes/_municipal.reports'
import { Route as MunicipalDetectionRouteImport } from './routes/_municipal.detection'
import { Route as MunicipalDashboardRouteImport } from './routes/_municipal.dashboard'
import { Route as MunicipalContractorsRouteImport } from './routes/_municipal.contractors'
import { Route as MunicipalBudgetRouteImport } from './routes/_municipal.budget'
import { Route as MunicipalAlertsRouteImport } from './routes/_municipal.alerts'

const NavigateRoute = NavigateRouteImport.update({
  id: '/navigate',
  path: '/navigate',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorRoute = ContractorRouteImport.update({
  id: '/contractor',
  path: '/contractor',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRoute = CitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const MunicipalRoute = MunicipalRouteImport.update({
  id: '/_municipal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MunicipalReportsRoute = MunicipalReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => MunicipalRoute,
} as any)
const MunicipalDetectionRoute = MunicipalDetectionRouteImport.update({
  id: '/detection',
  path: '/detection',
  getParentRoute: () => MunicipalRoute,
} as any)
const MunicipalDashboardRoute = MunicipalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => MunicipalRoute,
} as any)
const MunicipalContractorsRoute = MunicipalContractorsRouteImport.update({
  id: '/contractors',
  path: '/contractors',
  getParentRoute: () => MunicipalRoute,
} as any)
const MunicipalBudgetRoute = MunicipalBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => MunicipalRoute,
} as any)
const MunicipalAlertsRoute = MunicipalAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => MunicipalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/citizen': typeof CitizenRoute
  '/contractor': typeof ContractorRoute
  '/login': typeof LoginRoute
  '/navigate': typeof NavigateRoute
  '/alerts': typeof MunicipalAlertsRoute
  '/budget': typeof MunicipalBudgetRoute
  '/contractors': typeof MunicipalContractorsRoute
  '/dashboard': typeof MunicipalDashboardRoute
  '/detection': typeof MunicipalDetectionRoute
  '/reports': typeof MunicipalReportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/citizen': typeof CitizenRoute
  '/contractor': typeof ContractorRoute
  '/login': typeof LoginRoute
  '/navigate': typeof NavigateRoute
  '/alerts': typeof MunicipalAlertsRoute
  '/budget': typeof MunicipalBudgetRoute
  '/contractors': typeof MunicipalContractorsRoute
  '/dashboard': typeof MunicipalDashboardRoute
  '/detection': typeof MunicipalDetectionRoute
  '/reports': typeof MunicipalReportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_municipal': typeof MunicipalRouteWithChildren
  '/citizen': typeof CitizenRoute
  '/contractor': typeof ContractorRoute
  '/login': typeof LoginRoute
  '/navigate': typeof NavigateRoute
  '/_municipal/alerts': typeof MunicipalAlertsRoute
  '/_municipal/budget': typeof MunicipalBudgetRoute
  '/_municipal/contractors': typeof MunicipalContractorsRoute
  '/_municipal/dashboard': typeof MunicipalDashboardRoute
  '/_municipal/detection': typeof MunicipalDetectionRoute
  '/_municipal/reports': typeof MunicipalReportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/citizen'
    | '/contractor'
    | '/login'
    | '/navigate'
    | '/alerts'
    | '/budget'
    | '/contractors'
    | '/dashboard'
    | '/detection'
    | '/reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/citizen'
    | '/contractor'
    | '/login'
    | '/navigate'
    | '/alerts'
    | '/budget'
    | '/contractors'
    | '/dashboard'
    | '/detection'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/_municipal'
    | '/citizen'
    | '/contractor'
    | '/login'
    | '/navigate'
    | '/_municipal/alerts'
    | '/_municipal/budget'
    | '/_municipal/contractors'
    | '/_municipal/dashboard'
    | '/_municipal/detection'
    | '/_municipal/reports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MunicipalRoute: typeof MunicipalRouteWithChildren
  CitizenRoute: typeof CitizenRoute
  ContractorRoute: typeof ContractorRoute
  LoginRoute: typeof LoginRoute
  NavigateRoute: typeof NavigateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/navigate': {
      id: '/navigate'
      path: '/navigate'
      fullPath: '/navigate'
      preLoaderRoute: typeof NavigateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractor': {
      id: '/contractor'
      path: '/contractor'
      fullPath: '/contractor'
      preLoaderRoute: typeof ContractorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen': {
      id: '/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof CitizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_municipal': {
      id: '/_municipal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MunicipalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_municipal/reports': {
      id: '/_municipal/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof MunicipalReportsRouteImport
      parentRoute: typeof MunicipalRoute
    }
    '/_municipal/detection': {
      id: '/_municipal/detection'
      path: '/detection'
      fullPath: '/detection'
      preLoaderRoute: typeof MunicipalDetectionRouteImport
      parentRoute: typeof MunicipalRoute
    }
    '/_municipal/dashboard': {
      id: '/_municipal/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof MunicipalDashboardRouteImport
      parentRoute: typeof MunicipalRoute
    }
    '/_municipal/contractors': {
      id: '/_municipal/contractors'
      path: '/contractors'
      fullPath: '/contractors'
      preLoaderRoute: typeof MunicipalContractorsRouteImport
      parentRoute: typeof MunicipalRoute
    }
    '/_municipal/budget': {
      id: '/_municipal/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof MunicipalBudgetRouteImport
      parentRoute: typeof MunicipalRoute
    }
    '/_municipal/alerts': {
      id: '/_municipal/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof MunicipalAlertsRouteImport
      parentRoute: typeof MunicipalRoute
    }
  }
}

interface MunicipalRouteChildren {
  MunicipalAlertsRoute: typeof MunicipalAlertsRoute
  MunicipalBudgetRoute: typeof MunicipalBudgetRoute
  MunicipalContractorsRoute: typeof MunicipalContractorsRoute
  MunicipalDashboardRoute: typeof MunicipalDashboardRoute
  MunicipalDetectionRoute: typeof MunicipalDetectionRoute
  MunicipalReportsRoute: typeof MunicipalReportsRoute
}

const MunicipalRouteChildren: MunicipalRouteChildren = {
  MunicipalAlertsRoute: MunicipalAlertsRoute,
  MunicipalBudgetRoute: MunicipalBudgetRoute,
  MunicipalContractorsRoute: MunicipalContractorsRoute,
  MunicipalDashboardRoute: MunicipalDashboardRoute,
  MunicipalDetectionRoute: MunicipalDetectionRoute,
  MunicipalReportsRoute: MunicipalReportsRoute,
}

const MunicipalRouteWithChildren = MunicipalRoute._addFileChildren(
  MunicipalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MunicipalRoute: MunicipalRouteWithChildren,
  CitizenRoute: CitizenRoute,
  ContractorRoute: ContractorRoute,
  LoginRoute: LoginRoute,
  NavigateRoute: NavigateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
